// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/blog/[id]" | "/blog/edit/[id]" | "/blog/my-blogs" | "/categories/[type]" | "/contact" | "/new" | "/onboarding" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/sso-callback/[[...sso-callback]]" | "/unauthorized" | "/user-profile/[[...user-profile]]"
type AppRouteHandlerRoutes = "/api/search" | "/api/upload-auth" | "/api/userdata" | "/api/webhooks"
type PageRoutes = never
type LayoutRoutes = "/" | "/onboarding"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/search": {}
  "/api/upload-auth": {}
  "/api/userdata": {}
  "/api/webhooks": {}
  "/blog/[id]": { "id": string; }
  "/blog/edit/[id]": { "id": string; }
  "/blog/my-blogs": {}
  "/categories/[type]": { "type": string; }
  "/contact": {}
  "/new": {}
  "/onboarding": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/sso-callback/[[...sso-callback]]": { "sso-callback"?: string[]; }
  "/unauthorized": {}
  "/user-profile/[[...user-profile]]": { "user-profile"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/onboarding": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
