services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog?schema=public
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm prisma migrate deploy && pnpm dev --turbopack"

volumes:
  db-data:
