FROM node:20-alpine
RUN apk update && apk upgrade --no-cache
WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
# Activate pnpm without separate install
RUN corepack enable 

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY . .

EXPOSE 3000
CMD ["pnpm", "dev", "--turbopack"]
